#!groovy

pipeline {
  agent any

  stages {
    stage('Setup') {
      steps {
        git 'https://github.com/ansible/tower-example.git'
      }
    }

    stage('Provision') {
      steps {
        ansiblePlaybook playbook: 'helloworld.yml'
      }
    }
  }
}
