---
- name: Check nginx responds via HTTPS
  uri:
    url: https://localhost{{ jenkins_url_prefix }}{{ jenkins_health_check_path }}
    follow_redirects: none
    return_content: yes
    # TODO have it use the test cert
    validate_certs: no
  register: https_req
- name: Fail if HTTPS response isn't from Jenkins
  fail:
  when: "'Jenkins' not in https_req.content"
