---
- name: Enable network connections between nginx and Jenkins
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

# manage our own vhost file, because a) the template doesn't work for us, and b) we can use variables from `jdauphant.ssl-certs`
- name: Add vhost config file
  template:
    src: vhost.conf
    dest: "{{ nginx_vhost_path }}/jenkins.conf"
    owner: root
    group: root
    mode: 0644
  notify: reload nginx

- name: Restart nginx, if necessary
  meta: flush_handlers

- name: Check nginx redirects HTTP to HTTPS
  uri:
    url: http://{{ jenkins_hostname }}{{ jenkins_url_prefix }}{{ jenkins_health_check_path }}
    follow_redirects: none
    status_code: 301
  register: http_req
- name: Fail if HTTP doesn't redirect to HTTPS
  fail:
  when: not http_req.location.startswith('https://' + jenkins_hostname)

- name: Check nginx responds via HTTPS
  uri:
    url: https://localhost{{ jenkins_url_prefix }}{{ jenkins_health_check_path }}
    follow_redirects: none
    return_content: yes
    # TODO have it use the test cert
    validate_certs: no
  register: https_req
- name: Fail if HTTPS response isn't from Jenkins
  fail:
  when: "'Jenkins' not in https_req.content"
