---
- name: Create SSH directory
  file:
    path: "{{ jenkins_home }}/.ssh"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0700

- name: Write private SSH key
  copy:
    content: "{{ jenkins_ssh_private_key_data }}"
    dest: "{{ jenkins_home }}/.ssh/id_rsa"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0600

- name: Write public SSH key
  copy:
    content: "{{ jenkins_ssh_public_key_data }}"
    dest: "{{ jenkins_home }}/.ssh/id_rsa.pub"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0644
