---
- hosts: all
  name: Set up Jenkins
  vars:
    ansible_user: ec2-user
  become: true
  roles:
    - geerlingguy.jenkins
    # required for pip
    - geerlingguy.repo-epel
  tasks:

    - name: Restart Jenkins, if necessary
      meta: flush_handlers

    - name: Install dependencies
      yum:
        name:
          - git
          - python2-pip

    - name: Install dependencies for Jenkins modules
      pip:
        name: python-jenkins

    # http://stackoverflow.com/a/34522653/358804
    - name: Wait for Jenkins to be available
      uri:
        url: http://127.0.0.1:{{ jenkins_http_port }}
      register: result
      until: result.status == 200
      retries: 60
      delay: 1

    - name: Set up pipeline
      jenkins_job:
        config: "{{ lookup('file', 'files/job.xml') }}"
        name: test-auto
        user: "{{ jenkins_admin_username }}"
        password: "{{ jenkins_admin_password }}"
