---
- hosts: all
  name: Set up Jenkins
  vars:
    ansible_user: ec2-user
  become: true
  roles:
    - geerlingguy.jenkins
    # required for pip
    - geerlingguy.repo-epel
  tasks:

    - name: Ensure Jenkins is restarted
      meta: flush_handlers

    - name: Install dependencies
      yum:
        name:
          - git
          - python2-pip

    - name: Install dependencies for Jenkins modules
      pip:
        name: python-jenkins

    - name: Set up pipeline
      jenkins_job:
        config: "{{ lookup('file', 'files/job.xml') }}"
        name: test-auto
        user: "{{ jenkins_admin_username }}"
        password: "{{ jenkins_admin_password }}"
