---
- hosts: all
  name: Set up Jenkins
  vars:
    ansible_user: ec2-user
  become: true
  roles:

    - role: geerlingguy.jenkins
      java_packages:
        - java-1.8.0-openjdk
      jenkins_plugins:
        # https://plugins.jenkins.io/<ID>
        - workflow-aggregator

    # required for pip
    - geerlingguy.repo-epel

  tasks:

    - name: Ensure Jenkins is restarted
      meta: flush_handlers

    - name: Install dependencies
      yum:
        name:
          - git
          - python2-pip

    - name: Install dependencies for Jenkins modules
      pip:
        name: python-jenkins

    - name: Set up pipeline
      jenkins_job:
        config: "{{ lookup('file', 'files/job.xml') }}"
        name: test-auto
        user: "{{ jenkins_admin_username }}"
        password: "{{ jenkins_admin_password }}"
