---
- hosts: all
  name: Set up Jenkins
  vars:
    ansible_user: ec2-user
  tasks:

    - name: Install Jenkins
      become: true
      include_role:
        name: geerlingguy.jenkins
      vars:
        java_packages:
          - java-1.8.0-openjdk
